server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://39.106.164.190:3306/mysql?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zhangxian
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: utf-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  config: classpath:logback-spring.xml

