server:
  port: 1010

spring:
  datasource:
    url: jdbc:mysql://39.106.164.190:3306/mysql?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zhangxian
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: utf-8
    servlet:
      content-type: text/html
    prefix: classpath:templates/

  redis:
     database: 0
     host: 39.106.164.190
     port: 6379
     password:
     pool:
       max-active: 200
       max-wait: -1
       max-idle: 10
       min-idle: 0
     timeout: 1000
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  config: classpath:logback2-spring.xml
  level:
    com.zhangxian.xianredisapp: debug